version: "3.9"
services:
  prometheus:
    build:
      context: ../../
      args:
        HOST: ${HOST}
        USER: ${USER}
      dockerfile: ./dockers/cd/Dockerfile
    image: prometheus:1.0.0
    container_name: prometheus