replicaCount: 1

image:
  repository: rananoman/prometheus
  pullPolicy: Always
  tag: dev-latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 4000
  enabled: true

ingress:
  enabled: true
  host: devv.projects4.me
  path: /
  pathType: Prefix
  port: 80

resources: {}
