name: Deploy Prometheus | OVH

on:
  pull_request:
    types:
      - closed
  workflow_run:
    workflows: ["Run Prometheus test cases"]
    types: 
      - completed
    branches:
      - dev
      - qa

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Repository
        uses: actions/checkout@v3

      - name: Set up source and target branch name
        run: | 
          echo "SOURCE_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${GITHUB_BASE_REF}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            rananoman/prometheus:${{ env.SOURCE_BRANCH }}
            rananoman/prometheus:${{ env.TARGET_BRANCH }}-latest
          context: .
          file: docker/${{ env.TARGET_BRANCH }}/Dockerfile

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USERNAME }}
          key: ${{ secrets.OVH_KEY }}
          port: ${{ secrets.OVH_PORT }}
          script: |
            cd ${{ secrets.OVH_PROMETHEUS_HELM_PATH }}
            helm upgrade prometheus-${{ env.TARGET_BRANCH }} . -f values-${{ env.TARGET_BRANCH }}.yaml
