name: Deploy prometheus

env:
  DROPLET_KEY: ${{ secrets.DOKEY }}
  HOST: ${{ secrets.DOHOST }}
  USER: ${{ secrets.DOUSER }}

on:
  pull_request:
    types: [closed]
  push:
    branches: [ci/cd]

jobs:
  Deploy:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
      env:
        DROPLET_KEY: ${{ secrets.DOKEY }}
        HOST: ${{ secrets.DOHOST }}
        USER: ${{ secrets.DOUSER }}
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3
    - name: Deploy dist directory to droplet
      run: |
        touch droplet_key
        echo $DROPLET_KEY >> droplet_key
        # npm install
        # bower install
        # ember build --environment=${ENVIRONMENT}
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 64.225.108.167 >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
        chmod 600 droplet_key
        scp -i droplet_key -rp dist/ root@64.225.108.167:/home/web/prometheus/