name: Deploy Prometheus Dev

on:
  pull_request:
    types: [closed]
  push:
  workflow_run:
    workflows: ["Run Prometheus test cases"]
    types: 
      - completed

jobs:
  Deploy:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
      env:
        DROPLET_KEY: ${{ secrets.DOKEY }}
        HOST: ${{ secrets.DOHOST }}
        USER: ${{ secrets.DOUSER }}
        PROMETHEUS_PATH: ${{ secrets.PROM_PATH }}
        ENVIRONMENT: production
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3

    - name: Cache Node packages
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: node_modules
        key: npm-cache
    
    - name: Install Node modules
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        rm -rf node_modules/
        npm install

    - name: Create a file with Private Key
      run: |
        touch droplet_key
        echo "$DROPLET_KEY" > droplet_key

    - name: Build Prometheus
      shell: bash
      run: |
        set -a
        source prometheus-docker.env
        set +a
        echo $API_HOST_PRODUCTION
        node -e "console.log(process.env)"
        ember build --environment=$ENVIRONMENT

    - name: Deploy to Digital Ocean Droplet
      run: |
        chmod 600 droplet_key
        cp ci-cd/.htaccess dist/
        scp -i droplet_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp dist/ "$USER"@"$HOST":"$PROMETHEUS_PATH"