name: Deploy Prometheus Dev

on:
  pull_request:
    types: [closed]
  push:

jobs:
  Deploy:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
      env:
        DROPLET_KEY: ${{ secrets.DOKEY }}
        HOST: ${{ secrets.DOHOST }}
        USER: ${{ secrets.DOUSER }}
        PROMETHEUS_PATH: ${{ secrets.PROM_PATH }}
        ENVIRONMENT: production
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3

    - name: Check cache path
      run: |
        cd ~
        ls -al

    - name: Cache Node packages
      id: node-packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-cache

    - name: Create a file with Private Key
      run: |
        touch droplet_key
        echo "$DROPLET_KEY" > droplet_key

    - name: Build Prometheus
      run: ember build --environment=$ENVIRONMENT

    - name: Deploy to Digital Ocean Droplet
      run: |
        chmod 600 droplet_key
        cp ci-cd/.htaccess dist/
        scp -i droplet_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp dist/ "$USER"@"$HOST":"$PROMETHEUS_PATH"