name: Deploy prometheus

on:
  pull_request:
    types: [closed]
  push:
    branches: [ci/cd]

jobs:
  Deploy:

    runs-on: ubuntu-latest
    # container:
    #   image: rananoman/prometheus:1.0.0
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3
    - name: Deploy dist directory to droplet
      run: |
        touch private.key
        echo "$DROPLET_KEY" > private.key
        mkdir -p ~/.ssh/
        sudo chmod 600 private.key
        echo "$HOST" > ~/.ssh/known_hosts
        # ls
        # npm install
        # bower install
        # ember build --environment=${ENVIRONMENT}
        # mkdir -p ~/.ssh/
        # echo "$HOST" > ~/.ssh/known_hosts
        # touch ~/.ssh/known_hosts
        # ssh-keyscan -H 64.225.108.167 >> ~/.ssh/known_hosts
        # chmod 600 private.key
        scp -i private.key -rp private.key root@64.225.108.167:/home/web/prometheus/
      env:
        DROPLET_KEY: ${{ secrets.DOKEY }}
        HOST: ${{ secrets.DOHOST }}
        USER: ${{ secrets.DOUSER }}        