name: Deploy prometheus

on:
  pull_request:
    types: [closed]
  push:
    branches: [ci/cd]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image & deploy to prometheus
      run: docker compose -f dockers/cd/docker-compose.yaml up