name: Deploy prometheus

env:
  DROPLET_KEY: ${{ secrets.DOKEY }}
  HOST: ${{ secrets.DOHOST }}
  USER: ${{ secrets.DOUSER }}

on:
  pull_request:
    types: [closed]
  push:
    branches: [ci/cd]

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image & deploy to prometheus
      run: |
        touch droplet_key
        echo "$DROPLET_KEY" >> droplet_key
        docker compose -f dockers/cd/docker-compose.yaml up