name: Deploy Prometheus Dev

on:
  pull_request:
    types: [closed]
  push:

jobs:
  Deploy:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
      env:
        DROPLET_KEY: ${{ secrets.DOKEY }}
        HOST: ${{ secrets.DOHOST }}
        USER: ${{ secrets.DOUSER }}
        PROMETHEUS_PATH: ${{ secrets.PROM_PATH }}
        ENVIRONMENT: production
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3

    - name: Space taken by npm modules
      run: du -d 0 -h ~/.npm      

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache Node packages
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Create a file with Private Key
      run: |
        touch droplet_key
        echo "$DROPLET_KEY" > droplet_key

    - name: Install Node modules
      run: |
        npm install  

    - name: Build Prometheus
      run: ember build --environment=$ENVIRONMENT

    - name: Deploy to Digital Ocean Droplet
      run: |
        chmod 600 droplet_key
        cp ci-cd/.htaccess dist/
        scp -i droplet_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp dist/ "$USER"@"$HOST":"$PROMETHEUS_PATH"