name: Run Ember tests

on:
  pull_request:
    types:
      - "opened"
    branches: [ "ci/cd" ]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14.19.3
        cache: 'npm'

    - run: npm i -g ember-cli@4.1.1
    - run: npm install -g bower
    - run: npm install
    - run: bower install
    - run: ember -v
    - run: ember test