name: Run Ember tests

on:
  pull_request:
    types: [opened]
  push:
    branches: [ci/cd]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
    steps:
    - name: Checkout to Repo
      uses: actions/checkout@v3
    - name: Run docker container
      run: |
        npm install
        bower install
        ember test