name: Run Ember tests

on:
  pull_request:
    types: [opened]
  push:
    branches: [ci/cd]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
      volumes:
        - my_docker_volume:/prometheus      
    steps:
    - name: Run docker container
      run: ls -l