name: Run Ember tests

on:
  pull_request:
    types: [opened]
  push:
    branches: [ci/cd]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: node:17.6.0
    steps:
      - run: node --version