name: Run Ember tests

on:
  pull_request:
    types: [opened]
  push:
    branches: [ci/cd]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: ls

    - run: docker compose -f ci/docker-compose.yaml up