name: Run Prometheus tests cases

on:
  pull_request:
    types: [opened]
  
  push:
    branches: 
      - ci/cd

# jobs:
#   Build-and-Test:

#     runs-on: ubuntu-latest
#     container:
#       image: rananoman/prometheus:1.0.0
#     steps:
#     - name: Checkout to Repository
#       uses: actions/checkout@v3
#     - name: Run test cases
#       run: |
#         npm install
#         bower install
#         COVERAGE=true ember test
#     - name: Upload code coverage report
#       uses: actions/upload-artifact@v3
#       with:
#         name: code-coverage-report
#         path: coverage/

jobs:
  call-workflow-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout to Repository
        uses: actions/checkout@v3
      - name: check repo
        run: |
          ls -l
      - name: reuse workflow
        uses: .github/workflows/build.yml
      - name: check
        run: |
          ls -l


  # job2:
  #   runs-on: ubuntu-latest
  #   needs: call-workflow-build
  #   steps:
  #     - run: ls -l