name: Run Prometheus tests cases

on:
  pull_request:
    types: [opened]
  
  push:
    branches: 
      - ci/cd

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3
    - name: Run test cases
      run: |
      ls -l
      #   npm install
      #   bower install
      #   COVERAGE=true ember test
    - name: Cache Npm packages
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: /prometheus/node_modules
        key: ${{ runner.os }}-npm
    - if: ${{steps.cache-npm.outputs.cache-hit != 'true'}}
      run: npm install        
    # - name: Upload code coverage report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: code-coverage-report
    #     path: coverage/