name: Run Prometheus tests cases

on:
  pull_request:
    types: [opened]
  push:

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache Node packages
      id: node-packages
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Watch change in package.json
      id: watch-package-json
      uses: tj-actions/changed-files@v32
      with:
          files: "package.json"

    - name: Install Node modules
      if: |
        steps.watch-package-json.outputs.any_changed == 'true'
        || steps.node-packages.outputs.cache-hit != 'true'
      run: |
        rm -rf node_modules/
        npm install

    - name: Run Ember test
      run: |
        COVERAGE=true ember test
        
    - name: Upload Code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/