name: Run Ember tests

on:
  pull_request:
    types: [opened]
  push:
    branches: [ci/cd]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
    steps:
      - run: cd /prometheus
      - run: ls
      - run: ember -v
      - run: ember build