name: Run Prometheus tests cases

on:
  pull_request:
    types: [opened]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3
    - name: Run test cases
      run: |
        npm install
        bower install
        ember test