name: Run Prometheus test cases

on:
  pull_request:
    types: [opened,reopened]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: rananoman/prometheus:1.0.0
    steps:
    - name: Checkout to Repository
      uses: actions/checkout@v3

    - name: Cache Node packages
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: npm-cache

    - name: Install Node modules
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        rm -rf node_modules/
        npm install

    - name: Run Ember test
      run: |
        COVERAGE=true ember test
        
    - name: Upload Code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/